version: '2'

services:
  apache:
    environment:
      - PHPFPM_PORT=${DEVSTACK_PHPFPM_PORT}
    build: ./apache
    container_name: ds_apache2${DEVSTACK_PREF_NAME}
    ports:
      - '8082:80'
      - '8445:443'
    volumes:
      - "${DEVSTACK_WWWROOT}:/var/www/html"
      - "./data:/data"
    links:
      - php-fpm
  php-fpm:
    environment:
      - PHPFPM_PORT=${DEVSTACK_PHPFPM_PORT}
      - XDEBUG_PORT=${DEVSTACK_XDEBUG_PORT}
    build: 
      context: ./php-fpm
      args:
        XDEBUG_REMOTEIP : "${DEVSTACK_XDEBUG_REMOTEIP}"
        XDEBUG_IDEKEY : "${DEVSTACK_XDEBUG_IDEKEY}"
<<<<<<< HEAD
    container_name: ds_php-fpm${DEVSTACK_PREF_NAME}
=======
    container_name: ds_php-fpm
    ports:
      - '1521:1521'
      - '10386:10386'
      - '10389:10389'
>>>>>>> b6c9b937303ba2561d50fa3edeef7c637b5b6ab0
    volumes:
      - "${DEVSTACK_WWWROOT}:/var/www/html"
      - "./data:/data" 
      - "./php-fpm/setup:/setup"
