version: "2"
services:
  db:
    image: mysql:5
    container_name: ds_mysql${DEVSTACK_PREF_NAME}
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --innodb_file_format=barracuda
                --innodb_file_per_table=On
                --innodb_large_prefix=On
    environment:
      MYSQL_ROOT_PASSWORD: "bonimat"