services:
  db:
    image: postgres:17
    container_name: ${DEVSTACK_PREF_NAME:-ds}_pgsql
    restart: always

    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: bonimat
      POSTGRES_DB: pgdb
    ports:
      - 5433:5432
    volumes:
      - $DEVSTACK_PGDATA:/var/lib/postgresql/data