version: "2"
services:
  db:
    image: postgres
    container_name: ds_pgsql
    restart: always
    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: bonimat
      POSTGRES_DB: pgdb
      PGDATA: $DS_PGDATA
    ports:
      - 5432:5432