version: "2"
services:
  db:
    image: postgres:14
    container_name: ds_pgsql
    restart: always

    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: bonimat
      POSTGRES_DB: pgdb
    ports:
      - 5433:5432
    volumes:
      - $DEVSTACK_PGDATA:/var/lib/postgresql/data