version: "2"
services:
  db:
    image: postgres:11
    container_name: ds_pgsql${DEVSTACK_PREF_NAME}
    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: bonimat
      POSTGRES_DB: pgdb
    ports:
      - 5433:5432
    volumes:
      - $DS_PGDATA:/var/lib/postgresql/data