version: '2'
services:
  jenkins:
     container_name: ds_jenkins${DEVSTACK_PREF_NAME}
     image: jenkins:latest
     #build:
     #context: .
     #dockerfile: Dockerfile
     ports:
       - ${DEVSTACK_JENKINS_PORT}:8080
       - 50000:50000
     volumes:
       - ${DEVSTACK_JENKINS_HOME}:/var/jenkins_home